services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file: ".env"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      inception:
    restart: always
    init: true

  wordpress:
    build: 
      context: requirements/wordpress
      args:
        - GL_USER=${GL_USER}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: wordpress
    env_file: ".env"
    depends_on:
        mariadb:
            condition: service_healthy
    volumes:
      - wp:/var/www/html
    networks:
      inception:
    restart: always
    init: true

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    env_file: ".env"
    privileged: true
    volumes:
      - mariadb:/usr/local/mysql/var
    networks:
      inception:
    restart: always
    init: true
    healthcheck:
        test:		"mariadb-admin ping"
        interval:	5s
        timeout:	1m
        retries:	3

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/mhaouas/.data/database
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/mhaouas/.data/web
      o: bind

networks:
  inception:
    driver: bridge