FROM		    alpine:3.19.4

# Updating the existing package
RUN				[ "apk", "update" ]
RUN				[ "apk", "upgrade" ]

# Install NPM
RUN				[ "apk", "add", "npm" ]

# Install http-server
RUN				[ "npm", "install", "-g", "http-server" ]

# Create the static_page directory
RUN				[ "mkdir", "-p", "/var/www", "/var/www/html", "/var/www/html/static_page" ]

# Set it to the working directory
WORKDIR			/var/www/html/static_page

# Add the html file
ADD				[ "conf/index.html", "/var/www/html/static_page" ]

# Launch http-server
CMD				[ "http-server", "-p", "8080", "-d", "false" ]